
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: app-container
      image: my-app-image:latest
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 2
        successThreshold: 1
        failureThreshold: 3

