
apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  template:
    spec:
      containers:
      - name: app-container
        image: your-image:latest
        command: ["your-command", "arg1", "arg2"]
      restartPolicy: Never
  backoffLimit: 4

